### ISSUE TITLE
Good attempt! 

### ISSUE THREAD

**Issue by VigneshSahoo** [senesh-deshan/Google-Hash-Code-2020#1]
I got exactly the same score. My code is in Python though. Would you like to join my team for the Google Hashcode competition?

**Comment by senesh-deshan** [comment]
Thanks @VigneshSahoo , I would love to join your team, but I already have a team. By the way thanks again for asking.

**Comment by VigneshSahoo** [comment]
@senesh-deshan No problem. I noticed a small problem with your code. I guess you forgot to remove the duplicate entries from the input file. We need to rework on our codes. BTW, You are welcome :).

**Comment by senesh-deshan** [comment]
You mean this, right?

![image](https://user-images.githubusercontent.com/44916937/72997682-9b16e300-3e22-11ea-952d-b18f313c10af.png)

Thanks for pointing it out. This code is not the perfect solution and it can be optimized and bugs fixed in the future.

Anyway this is just a simple solution with a simple logic which was written to inspire people and give them a start. There may be so many better solutions for this problem.

**Comment by VigneshSahoo** [comment]
Yes, I meant that point only. Yeah, optimization is the key. Best of luck.
