### ISSUE TITLE
Failed Test Case

### ISSUE THREAD

**Issue by SockPastaRock** [senesh-deshan/Google-Hash-Code-2020#5]
This is a great attempt and it appears to succeed the given test cases extremely fast.

However, this solution does not solve the problem in general. Applying your solution to some custom inputs (e.g. [8, 8, 10, 11], w/ target 17) yields incorrect results. See image below.

![failed_test](https://user-images.githubusercontent.com/15906298/73224742-75e2e700-4138-11ea-8fca-b273e5d49932.png)

**Comment by VigneshSahoo** [comment]
This is the correct answer because same Slices are not allowed. @SockPastaRock . Then the max score will be 11 only!

**Comment by 0xDEADBEE7** [comment]
Two different pizzas may have the same number of slices according to the question's specification. (see below)

![question_specification](https://user-images.githubusercontent.com/15906298/73233329-27dbdc80-4154-11ea-9631-b398862c173f.png)

**Comment by 0xDEADBEE7** [comment]
Additionally, the algorithm you specify will have the same issue for the input [7, 8, 10, 11]. Correct solution should be 17.

![failed_test2](https://user-images.githubusercontent.com/15906298/73233454-9d47ad00-4154-11ea-95e9-ae842c581a21.png)

**Comment by VigneshSahoo** [comment]
![Screenshot_20200128-085944](https://user-images.githubusercontent.com/54697837/73233460-a19fb480-41ac-11ea-8503-350d75c5dc7d.jpg)
We are allowed to choose only one of same type pizzas.

**Comment by 0xDEADBEE7** [comment]
We are always choosing pizzas of different types but **two different types of pizza may have the same number of slices**

**Comment by VigneshSahoo** [comment]
Go with the same number of slices then. All the best for next year's challenge. :-D

**Comment by senesh-deshan** [comment]
@SockPastaRock  and @VigneshSahoo 
As I think both of your arguments are fair because the problem document is a little ambiguous and it's difficult to decide whether we should ignore duplicated entries or not.

But look at the output files we have already submitted to the Judge System. Those files scored maximum points even though there are duplicated pizza numbers. So as I believe I agree with @SockPastaRock  **it is not necessary to remove duplicate entries**. 

> We are always choosing pizzas of different types but **two different types of pizza may have the same number of slices**

We are asked to choose only one from each type and problem has given us some pizzas with same number of slices. If we chose two duplicated pizzas with different index numbers, we are not wrong because we have chosen two pizzas and that is what we are asked to do. We get maximum points even if we have not cared about duplicated entries.

**Comment by senesh-deshan** [comment]
BTW thanks @SockPastaRock pointing out that issue in my code.
Problem was with the termination condition of the main loop.
I fixed it and updated.
Please let me know if there is any issue and you are welcome to correct me in the future also.

**Comment by 0xDEADBEE7** [comment]
After pulling your changes, there are still some test cases where this algorithm will fail. See below. I don't think it's an issue with your implementation of this algorithm but rather, it's a problem with this algorithm itself.

![failed_test3](https://user-images.githubusercontent.com/15906298/73239841-48fbf780-416b-11ea-82ae-b4c3b88a8746.png)
Expected result: 17

![failed_test4](https://user-images.githubusercontent.com/15906298/73239844-4b5e5180-416b-11ea-9809-28e2f659cf5b.png)
Expected result: 17

**Comment by senesh-deshan** [comment]
@SockPastaRock Good, I'll look into it try to fix.

**Comment by senesh-deshan** [comment]
I fixed it. Please have a look at it.

**Comment by 0xDEADBEE7** [comment]
This solution now works but it means that the worst case time complexity will be O(2^n). For the given test cases it still resolves very fast. I'm not sure if those tests are representative of the average case or if they are _generous_ test cases. It would be good to explore what happens if you are to generate random test cases with an even distribution of numbers. I expect the performance will stay close to O(n) but I haven't tested it.

I've given you a PR with some worst case test cases which will demonstrate the O(2^n) time complexity (see pic below, this test case will take an extremely long time to resolve). If your average case time complexity is good, I think this is a good solution.

![worst_case_time](https://user-images.githubusercontent.com/15906298/73317637-c0ca3080-4204-11ea-8866-af4ebf991d09.png)

**Comment by senesh-deshan** [comment]
Thank you for your effort @SockPastaRock
