### ISSUE TITLE
Check out my solution

### ISSUE THREAD

**Issue by ekosman** [senesh-deshan/Google-Hash-Code-2020#7]
I posted my iterative solution here. It uses only one loop, i.e. no nested loops and I apply optimization for trimming the search space and speeding up the calculations.

https://github.com/ekosman/Google-Hash-Code-2020/tree/master/More%20Pizza

I'll add the outputs later.

**Comment by senesh-deshan** [comment]
I admit that my code is may not be the most efficient solution but it has the ability to solve the problem in less than half a second. There is still room for improvement.

It seems to be that you have tried a different approach.
Your effort is really good and appreciable. 👏

But the main problem in your code that I see is the execution time because, it is around 10 hours as I guess. That is a bigger problem right?

It seems to be that you have a good experience with programming and algorithm development.
You can put a little more more effort and try to avoid more negligible combinations so you can increase the efficiency of the code.

By the way good luck for the Hash Code 2020!  ✌️

**Comment by ekosman** [comment]
Firstly, thanks for the complements compliments.

I have one question about your algorithm. It seems like it follows a greedy approach. Is it guaranteed to find the best solution?

**Comment by senesh-deshan** [comment]
It does look like the greedy approach at first glance but it is actually not the greedy approach. I can guarantee that it finds the best solution.

**Comment by ekosman** [comment]
Ok thanks.

Very good solution though, good luck!

**Comment by senesh-deshan** [comment]
My pleasure
